---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: flatly
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(flexdashboard)
library(patchwork)
library(p8105.datasets)
```

```{r collapse=TRUE}
data("ny_noaa")

ny_noaa_tidy = 
  ny_noaa %>% 
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>% 
  mutate(
    prcp = prcp/10,
    tmax = as.numeric(tmax),
    tmax = tmax/10, 
    tmin = as.numeric(tmin),
    tmin = tmin/10, 
    snow_mm = snow,
    snow = round(snow_mm * 0.03937 * 4) / 4) %>% 
  drop_na(tmax, tmin) %>% 
  sample_n(1000)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Scatterplot

```{r}
ny_noaa_tidy %>% 
  mutate(text_label = 
           str_c("Year: ", year, "\nMonth: ", month, "\nDay: ", day)) %>% 
  plot_ly(
    x = ~tmin, y = ~tmax, color = ~year, text = ~text_label,
    alpha = .5, type = "scatter", mode = "markers")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Boxplot

```{r}
ny_noaa_tidy %>% 
  mutate(month = month.name[as.numeric(month)]) %>% 
  mutate(month = fct_reorder(month, tmax)) %>% 
  plot_ly(
    y = ~tmax, x = ~month, color = ~month,
    type = "box", colors = "viridis")
```

### Barplot 

```{r}
ny_noaa_tidy %>% 
  count(id) %>% 
  mutate(id = fct_reorder(id, n)) %>% 
  plot_ly(
    x = ~id, y = ~n, color = ~id, 
    type = "bar", colors = "viridis") %>% 
  layout(showlegend = FALSE)
```

